travis:
  secure:
    BINSTAR_TOKEN: VD20uFEZ7VeshRQSHX39ys1k2MLO0oG52EoDyCWP+VWGD1sgMgWWiBb23+oUJMzfosdMSYCkixo+VCZcJOmH6cPm3F/OGWzV0xt9k9r84pjs+xdDZcF8/ZtGp0oqML+bIQI0ndsQ9ATcMwi0hZ0J2jnXQf4os6ltGP5mKeEUy8ZIjns4RyyMfB0zvwz0DGy++4bleoBvwuEJ2nVOD4wqcDdfPFTJ2osifikFyanot+R+ZGS/5aPwWEvE6bOJvjdyFXuEqG8t+6N9byiDyUQUyYwcg9Jh6maBEtIbd/OpXArhMT+2Da+KNipkPE10NHZnJtRqnIQ2BdzsiEtMkfjUC7gOqrb0ByPkxAnF/h+3tu2UT/HDNXhSGcrlXrBgGEbtHbMzLEK5Uff9nm+5covQXdkGKSO04rIV/zZx4AKZ6G0y83V0oOCVMktbD7uPHsA5rYs+8wwz5Dy44crNZmd/DW6KDlBJwvImACndNWjWZogcUGbAC9Fm5wSrDcCRcAMo2mVDJ9jj28CWow9oWHYKWjBCwgVTXMu3V/28GyldDRD7h0rxwKd3vAO3c094XdzRK8qRVgMzvGww1J6dboGaRaYY6B2FA2ASWjUycA7P2TjFZ3lqj+qg8D7E0xgMyJjnqLsgt6uPg1RCfpTadkXrYIKIdCAF0mLJx2gybQLaBUM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
